-- CRUD (Create, Read, Update, Delete) 
CREATE TABLE CUSTOMER_TABLE 
(Cust_ID int primary key, 
First_Name VARCHAR(30), 
Last_Name VARCHAR(30), 
Sales float, 
Email VARCHAR(30)) 


INSERT INTO CUSTOMER_TABLE VALUES (1, 'Yesim', 'Bulgan', 2000, 'yesimb@gmail.com'); 
SELECT * FROM CUSTOMER_TABLE; 
DELETE FROM CUSTOMER_TABLE WHERE Cust_ID = 1 


-- All Customers Table 
SELECT * FROM SH.CUSTOMERS; 

-- Null 
SELECT * FROM SH.CUSTOMERS 
WHERE CUST_MARITAL_STATUS IS NULL; 

-- Not Null 
SELECT CUST_FIRST_NAME, CUST_EMAIL 
FROM SH.CUSTOMERS 
WHERE CUST_EMAIL IS NOT NULL; 

-- COALESCE 
SELECT CUST_FIRST_NAME, COALESCE(CUST_CREDIT_LIMIT, 0) AS CREDIT 
FROM SH.CUSTOMERS; 

-- NVL Function 
SELECT CUST_FIRST_NAME, NVL(CUST_CREDIT_LIMIT, 0) AS CREDIT 
FROM SH.CUSTOMERS; 

-- NVL2 Function
SELECT CUST_FIRST_NAME, NVL2(CUST_CREDIT_LIMIT, 'Has Credit', 'No Credit') AS CREDIT_STATUS 
FROM SH.CUSTOMERS; 

-- First and Lastnames of Customers 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME FROM SH.CUSTOMERS; 

-- First 5 Customers 
SELECT * FROM SH.CUSTOMERS WHERE ROWNUM <= 5; 

-- All Countries 
SELECT * FROM SH.COUNTRIES; 

-- First Names and Year of Births 
SELECT CUST_FIRST_NAME, CUST_YEAR_OF_BIRTH FROM SH.CUSTOMERS; 

-- Total Customers
SELECT COUNT(*) AS TOTAL_CUSTOMER 
FROM SH.CUSTOMERS; 

-- First Names, Last Names and Emails 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_EMAIL  
FROM SH.CUSTOMERS; 

-- All Cities Province ASC 
SELECT CUST_CITY FROM SH.CUSTOMERS  
ORDER BY CUST_CITY ASC; 

-- Customers who EFF From 2005 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_EFF_FROM  
FROM SH.CUSTOMERS 
WHERE CUST_EFF_FROM > DATE '2005-01-01'; 

-- CITY ID 
SELECT * FROM SH.CUSTOMERS 
WHERE CUST_CITY_ID = 51057 OR CUST_CITY_ID = 51062; 

-- Unique Cities 
SELECT DISTINCT CUST_CITY FROM SH.CUSTOMERS; 

-- Last Names Started with A 
SELECT * FROM SH.CUSTOMERS WHERE CUST_LAST_NAME LIKE 'A%'; 

-- Amount Sold Between 50 and 60 
SELECT CUST_ID, AMOUNT_SOLD  
FROM SH.SALES 
WHERE AMOUNT_SOLD BETWEEN 50 AND 60 
ORDER BY AMOUNT_SOLD; 

-- Cust ID > 1000 or Amount Sold > 55 
SELECT CUST_ID, AMOUNT_SOLD  
FROM SH.SALES 
WHERE CUST_ID > 1000 OR AMOUNT_SOLD > 55 
ORDER BY AMOUNT_SOLD DESC; 

-- Sort Products by Price 
SELECT * FROM SH.PRODUCTS; 
SELECT PROD_NAME,PROD_LIST_PRICE, 
ROW_NUMBER() OVER (ORDER BY PROD_LIST_PRICE DESC) AS PRICE_RANK 
FROM SH.PRODUCTS 
ORDER BY PRICE_RANK; 

-- EFF From First 10 days of the month 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_EFF_FROM, 
EXTRACT(DAY FROM CUST_EFF_FROM) AS GUN, 
TO_CHAR(CUST_EFF_FROM, 'MONTH') AS AY, 
EXTRACT(YEAR FROM CUST_EFF_FROM) AS YIL 
FROM SH.CUSTOMERS  
WHERE EXTRACT(DAY FROM CUST_EFF_FROM) <= 10 
ORDER BY CUST_EFF_FROM; 

-- Category of Products 
SELECT PROD_NAME, PROD_SUBCATEGORY, 
CASE PROD_SUBCATEGORY_ID 
WHEN 2035 THEN 'Training Aids and Equipment' 
WHEN 2031 THEN 'Baseball' 
WHEN 2036 THEN 'Bats' 
ELSE 'Other'
END AS PROD_CAT 
FROM SH.PRODUCTS; 

-- Product Price Analyse 
SELECT PROD_NAME, PROD_LIST_PRICE, 
CASE  
WHEN PROD_LIST_PRICE > 900 THEN 'Expensive' 
WHEN PROD_LIST_PRICE > 300 THEN 'Average' 
ELSE 'Cheap' 
END AS Price_Cat, 
NVL(PROD_LIST_PRICE, 0) AS LIST_PRICE 
FROM SH.PRODUCTS; 

-- Email before @ 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, 
LOWER(CUST_EMAIL) AS EMAIL_LOWER, 
SUBSTR(CUST_EMAIL, 1, INSTR(CUST_EMAIL, '@') - 1) AS USERNAME 
FROM SH.CUSTOMERS; 

-- Product Number by Product Name 
SELECT PROD_ID, COUNT(*) AS PRODUCT_COUNT 
FROM SH.PRODUCTS 
GROUP BY PROD_ID; 
ORDER BY PROD_ID; 

-- Products with Avg_Price > 600 by Product ID 
SELECT PROD_ID, AVG(PROD_LIST_PRICE) AS AVG_PRICE 
FROM SH.PRODUCTS 
GROUP BY PROD_ID 
HAVING AVG(PROD_LIST_PRICE) > 600; 

-- Customer - Country Inner Join 
SELECT e.CUST_FIRST_NAME, e.CUST_LAST_NAME, d.COUNTRY_NAME 
FROM SH.CUSTOMERS e 
INNER JOIN SH.COUNTRIES d  
ON e.COUNTRY_ID = d.COUNTRY_ID; 

-- Customer - Country Left Join 
SELECT e.CUST_FIRST_NAME, e.CUST_LAST_NAME, d.COUNTRY_NAME 
FROM SH.CUSTOMERS e 
LEFT JOIN SH.COUNTRIES d 
ON e.COUNTRY_ID = d.COUNTRY_ID; 

-- Customer - Country Right Outer Join 
SELECT e.CUST_FIRST_NAME, e.CUST_LAST_NAME, d.COUNTRY_NAME 
FROM SH.CUSTOMERS e 
RIGHT JOIN SH.COUNTRIES d 
ON e.COUNTRY_ID = d.COUNTRY_ID; 

-- Customer - Country Full Outer Join 
SELECT e.CUST_FIRST_NAME, e.CUST_LAST_NAME, d.COUNTRY_NAME 
FROM SH.CUSTOMERS e 
Full JOIN SH.COUNTRIES d 
ON e.COUNTRY_ID = d.COUNTRY_ID; 

-- Count of the Products 
SELECT PROD_ID, COUNT(*) AS PROD_COUNT 
FROM SH.PRODUCTS 
GROUP BY PROD_ID 
HAVING COUNT(*) =  
(SELECT MAX(PROD_COUNT) FROM ( 
SELECT COUNT(*) AS PROD_COUNT  
FROM SH.PRODUCTS 
GROUP BY PROD_ID)); 

-- Top Customers by Sales for each Product 
SELECT CUST_ID, AMOUNT_SOLD, PROD_ID 
FROM SH.SALES E1 
WHERE AMOUNT_SOLD = (SELECT MAX(AMOUNT_SOLD)  
FROM SH.SALES E2  
WHERE E2.PROD_ID = E1.PROD_ID); 

-- The Product with the 2nd Highest Price 
SELECT E1.PROD_NAME, E1.PROD_LIST_PRICE, E1.PROD_ID 
FROM SH.PRODUCTS E1 
WHERE 2 = ( 
SELECT COUNT(DISTINCT E2.PROD_LIST_PRICE) 
FROM SH.PRODUCTS E2 
WHERE E2.PROD_ID = E1.PROD_ID  
AND E2.PROD_LIST_PRICE >= E1.PROD_LIST_PRICE 
) 
ORDER BY E1.PROD_ID; 

-- Customer, Product, Country 
SELECT 'Customer' AS TYPE, CUST_FIRST_NAME || ' ' || CUST_LAST_NAME AS NAME, TO_CHAR(CUST_ID) AS ID 
FROM SH.CUSTOMERS 
UNION 
SELECT 'Product' AS TYPE, PROD_NAME AS NAME, TO_CHAR(PROD_ID) AS ID 
FROM SH.PRODUCTS 
UNION 
SELECT 'Country' AS TYPE, COUNTRY_NAME AS NAME, TO_CHAR(COUNTRY_ID) AS ID 
FROM SH.COUNTRIES 
ORDER BY TYPE, NAME; 

-- UNION ALL 
SELECT * FROM SH.CUSTOMERS; 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_ID 
FROM SH.CUSTOMERS 
WHERE CUST_ID = 16561 
UNION ALL 
SELECT CUST_FIRST_NAME, CUST_LAST_NAME, CUST_ID 
FROM SH.CUSTOMERS 
WHERE CUST_CREDIT_LIMIT > 5000; 

-- CTE 
SELECT * FROM SH.SALES; 
WITH AMOUNT_SOLD AS ( 
SELECT CUST_ID, AMOUNT_SOLD 
FROM SH.SALES 
WHERE AMOUNT_SOLD > (SELECT AVG(AMOUNT_SOLD) FROM SH.SALES) 
) 
SELECT D.PROD_ID, COUNT(*) AS PROD_ID_COUNT 
FROM SH.SALES S 
JOIN SH_PRODUCTS D ON H.PROD_ID = D.PROD_ID 
GROUP BY D.PROD_ID 
ORDER BY PROD_ID_COUNT DESC; 

-- Product's Price Ranking and Their Categories 
SELECT * FROM SH.PRODUCTS; 
SELECT E.PROD_NAME, E.PROD_LIST_PRICE, D.PROD_CATEGORY, 
RANK() OVER (ORDER BY E.PROD_LIST_PRICE DESC) AS PRICE_RANK, 
RANK() OVER (PARTITION BY E.PROD_ID ORDER BY E.PROD_LIST_PRICE DESC) AS PROD_RANK, 
ROUND(PERCENT_RANK() OVER (ORDER BY E.PROD_LIST_PRICE) * 100, 2) AS PRICE_PER 
FROM SH.PRODUCTS E 
JOIN SH.PRODUCTS D ON E.PROD_ID = D.PROD_ID 
ORDER BY E.PROD_LIST_PRICE DESC; 